### ISSUE TITLE
generate pdf automatically

### ISSUE THREAD

**Issue by changjian-k2k** [EMVA1288/emva1288#116]
is there any plan to generate pdf file automatically, rather than a tex file.

**Comment by fariza** [comment]
The original template was created in latex, that is why we generate a tex file. Also, generate a complex PDF directly is not that easy.

Create a simple script that generates the final PDF from the tex file is not hard at all, you just need to make sure to have a working latex compiler.

I am closing this, but if you feel you need more information or something is missing, please let me know
