### ISSUE TITLE
Dark Current from variance (DN)

### ISSUE THREAD

**Issue by newkew** [EMVA1288/emva1288#136]
Please could you confirm the calculation of the Dark Current from variance (in results.py line 616 to 606)
you write `u_I_var_DN with fit[0] / self.K * 1e9` from s2_ydark versus texp

For me, the result must be `u_I_var_DN with fit[0] * 1e9` in DN²/s
and the compute u_I_var (in e-/s) given by u_I_var_DN / self.K **2

Kewin

**Comment by fariza** [comment]
This follows the standard release 3.1 section 7, please explain why do you think this is not the right thing to do

**Comment by newkew** [comment]
Fariza, thank you for your answer 
In fact, it's just a misunderstanding not an issue. To obtain µc by var I need to divide the slope (variance vs. exposure) by K² not K
In your code, it's done but I didn't quite understand how it's clearer now

Noted, it is clearler in realease 4 (7.1 page 27) 
Best
