### ISSUE TITLE
Inconsistency in bin width and bin value calculation between Source Code and EMVA1288 Standard

### ISSUE THREAD

**Issue by paolomunarini** [EMVA1288/emva1288#149]
The function `routines.Histogram1288(img, Qmax)` implements the bin width calculation as follows:

```
W = int(np.ceil(1. * q / (Qmax - 1)))
```

Following the standard, the bin width should be calculated as

```
W = int(np.floor(1. * q / Qmax)) + 1
```

References:

- Rev3.1: Section 8.4, Eqn 52
- Rev4.0 - general: Section 8.8, Eqn 64

**Comment by fariza** [comment]
@paolomunarini can you make an MR adding tests to make sure we don't make the same mistake twice

**Comment by paolomunarini** [comment]
By "adding tests" do you mean a black box test of the Histogram1288 routine?

**Comment by fariza** [comment]
Yes, some simple data with known results
