### ISSUE TITLE
Issue in Linearity Error computation - Inconsistency with plotting

### ISSUE THREAD

**Issue by paolomunarini** [EMVA1288/emva1288#150]
There is a difference between the indexes used in the computation of the Linearity Error minimum and maximum and the ones used in plotting the Linearity Error.

In particular, in the LE computation, the **maximum** index is `index_linearity_max + 1` (`results.py:553-582`), where in plotting it is `index_linearity_max` (`plotting.py:330-331` and `plotting.py:351-354`).

This difference leads to an inconsistency between plots and data in the cases where the maximum LE is in the last point of the series.

This can be verified with the reference dataset _EMVA1288_ReferenceSet_003_Simulation_12Bit_

I'd propose to use `index_linearity_max` in both LE computation and plotting cases, while still using `index_linearity_max+1` in the fit which is correct.

**Comment by fariza** [comment]
@paolomunarini please make an MR addressing this changes

**Comment by fariza** [comment]
Fixed by #154
