### ISSUE TITLE
matplotlib x/y-labels sould be raw strings

### ISSUE THREAD

**Issue by bebuch** [EMVA1288/emva1288#162]
Currently a lot of the tests warn about invalid escape sequences which result from the tex-like syntax of matplotlib labels.

```
  /src/emva1288/process/plotting.py:135: DeprecationWarning: invalid escape sequence '\m'
    xlabel = '$\mu_p$ [mean number of photons/pixel]'
```

That can be avoided by masking all backslashes (`'\\'`) or simply use raw strings (`r'\'`).

**Comment by fariza** [comment]
Fixed by #163
