### ISSUE TITLE
How to create a Report?

### ISSUE THREAD

**Issue by bebuch** [EMVA1288/emva1288#165]
Again here the question, so that others will find it later ;-)

What code do you need to run to create a full report?

**Comment by zhaoyutong43210** [comment]
you run https://github.com/EMVA1288/emva1288/blob/master/doc/examples/sample_report.py and you will get a `reprot.tex`, run 'pdflatex report.tex' under the directory will generate a pdf file to view.

**Comment by bebuch** [comment]
Thank you!
