### ISSUE TITLE
Move to Python 3.7 as minimum version

### ISSUE THREAD

**Issue by bebuch** [EMVA1288/emva1288#168]
The setup file currently lists Python 3.6 as the oldest supported version. I propose that we move to version 3.7.

Motivation:

- 3.6 is out of support (end-of-life was 23 Dec 2021)
- 3.7 is the oldest version with support (end-of-life is 27 Jun 2023)
- Debian (oldstable) Buster is probably the Linux distribution with the oldest Python: 3.7 is it's standard version
  - ignoring RHEL here ;-)
- `pytest-flake8` requires 3.7 as minimum

The current CI pipelines test only against the current version 3.10.

@fariza @aturcotte @louvervecken @zhaoyutong43210 If you agree, I will adjust the setup and adjust the CI so that it tests against Python 3.7 and the latest Python version.

**Comment by louvervecken** [comment]
Agree to move away from 3.6 as it's no longer supported. 
It looks like we have no version requirements on our other dependencies at the moment?

**Comment by fariza** [comment]
why don't we move to 3.8?

**Comment by fariza** [comment]
For me is more in the resources that we have to "support" older versions. 
I would say, let's go for 3.8 as middle ground
