### ISSUE TITLE
SNR_max_dB calculation is wrong.

### ISSUE THREAD

**Issue by mwuetschner** [EMVA1288/emva1288#24]
The CMX comparison for the 12 Bit CCD Reference set shows that the SNR_max_dB calculation is wrong. 

SNR_max_dB                          95.4485571343       41.4527816691433     FAIL

You are not using the wrong log function:

return 20. * np.log(self.SNR_max) 
instead of 
return 20. * np.log10(self.SNR_max)

**Comment by fariza** [comment]
Should work now please confirm

**Comment by mwuetschner** [comment]
Works now.
