### ISSUE TITLE
Problems saving XML from result.

### ISSUE THREAD

**Issue by mwuetschner** [EMVA1288/emva1288#25]
Using WinPython I get an error when I want to write an XML with the result.xml function.
File "P:\SOFTWARE\Development\Python\WinPython-64bit-3.4.3.4\python-3.4.3.amd64\lib\site-packages\emva1288\routines.py", line 321, in dict_to_xml
    filename.write(t)
AttributeError: 'str' object has no attribute 'write'

I had to make these changes:
   
    myfile = open(filename, 'bw');
    myfile.write(t);
    #filename.write(t)

In this function:

    def dict_to_xml(d, root='results', filename=None):
    '''
    Takes a dict and return a well formed xml string
    '''
    def key_to_xml(d, r):
        '''
        Recursive call to add the key/value from dict to the r element tree
        If the value is an array joint the values casted as strings
        with whitespaces separator
        if the value is something else, it is casted as string
        '''
        for k in d.keys():
            e = etree.SubElement(r, k)
            # when the value for the key is a dict, call the function again
            if isinstance(d[k], dict):
                r.append(key_to_xml(d[k], e))

            # if the value is an array
            # add the values of the array as a string separated by whitespaces
            # Note to self: add other array types as needed
            elif isinstance(d[k], np.ndarray):
                a = [str(x) for x in d[k]]
                e.text = ' '.join(a)

            # if something else, just add the corresponding string value
            else:
                e.text = str(d[k])
        return r

    tree = etree.Element(root)
    xml = key_to_xml(d, tree)

    t = etree.tostring(xml, pretty_print=True)
    if filename is None:
        return t
    myfile = open(filename, 'bw');
    myfile.write(t);
    #filename.write(t)

**Comment by fariza** [comment]
Should work now, please confirm

**Comment by mwuetschner** [comment]
Works now.
