### ISSUE TITLE
Importing the report submodule module fails on Python 2.7

### ISSUE THREAD

**Issue by adrienbailly** [EMVA1288/emva1288#32]
Configuration:
* Windows 7 64bit
* Anaconda 2.3.0 64bit
* IPython QtConsole 3.2.0
* Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 16:44:52) [MSC v.1500 64 bit (AMD64)]

Error message:
```
$ import emva1288
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-d08faac68be4> in <module>()
----> 1 import emva1288

D:\Program Files (x86)\Anaconda-2.3.0-64bit\lib\site-packages\emva1288\__init__.py in <module>()
     11 from .results import Results1288
     12 from .plotting import Plotting1288
---> 13 from .report import report
     14 
     15 

D:\Program Files (x86)\Anaconda-2.3.0-64bit\lib\site-packages\emva1288\report\report.py in <module>()
      4 from distutils.dir_util import copy_tree
      5 from collections import namedtuple
----> 6 from tempfile import TemporaryDirectory
      7 
      8 from .. results import Results1288

ImportError: cannot import name TemporaryDirectory
```

It seems that in python 2.7 the tempfile does not have a TemporaryDirectory method (https://docs.python.org/2/library/tempfile.html).

**Comment by fariza** [comment]
Yes, that was added in 3.x. Do you need the report submodule right now?
If not, just remove the `from .report import report` in `__init__.py` and it should work while I figure something out.

**Comment by fariza** [comment]
What exactly are you trying to do?
Because another option is not to include the hole `emva1288` module, but just the submodules
And use them in the same way as they are used in the `full_emva_process` example

```
from emva1288.results import Results1288
from emva1288.plotting import Plotting1288
from emva1288.data import Data1288
from emva1288.loader import LoadImageData
from emva1288.parser import ParseEmvaDescriptorFile

dir_ = '/home/work/1288/datasets/'
fname = 'EMVA1288_ReferenceSet_001_CCD_12Bit/EMVA1288_Data.txt'

info = ParseEmvaDescriptorFile(os.path.join(dir_, fname))
imgs = LoadImageData(info.info)
dat = Data1288(imgs.data)
res = Results1288(dat)
res.print_results()
plot = Plotting1288(res)
plot.plot()
```

Again, this is a workaround until I figure something out

**Comment by fariza** [comment]
Hmmm, that is not going to work

**Comment by adrienbailly** [comment]
For now I have replaced TemporaryDirectory by mkdtemp in report.py and the
simple example runs fine (e.results() e.plots()) and generates the plots.

If I run sample_report.py I got another error:

%run sample_report.py
INFO:Parser:Opening D:\Projet\PLL\Characterization\Script
EMVA1288\dataset\EMVA1288_ReferenceSet_003_Simulation_12Bit\EMVA1288_Data.txt
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
D:\Projet\PLL\Characterization\Script EMVA1288\sample_report.py in
<module>()
     12
     13 # Description of the setup
---> 14 setup = emva1288.report.info_setup()
     15 setup.standard_version = 3.1
     16

AttributeError: 'module' object has no attribute 'info_setup'

But this might not be related to the TemporaryDirectory issue...

Anyway I don't need the report generation for now. My goal was to try the
module and then build a dataset/descriptor file using images from the
sensor we developped.




2015-07-29 18:10 GMT+02:00 Federico Ariza <notifications@github.com>:

**Comment by fariza** [comment]
If you are storing the files in the hd that's a fine way to do it, but if you are taking them and want to store them into a database, I would recommend to store just the result of `LoadImageData`, that is a reduced dataset that preserves all the information needed for the `EMVA1288` test and keeps data as integers so no problem with floating point precision.

**Comment by fariza** [comment]
I made several changes, between them I removed the dependency on the tempfile module.
Please check to see if it works now.

**Comment by adrienbailly** [comment]
The report generator works now! Thank you.

**Comment by fariza** [comment]
Cool, there will be a couple of extra changes while everything settles.
We're working on a final template, so things may change
